# Generated by Django 5.2 on 2025-06-29 09:34

import apps.products.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/images/')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity_per_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('units_in_stock', models.IntegerField(default=0)),
                ('units_on_order', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('discontinued', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('supplier', models.ForeignKey(blank=True, db_column='supplier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.supplier')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('small', 'Small'), ('base', 'Base'), ('thumbnail', 'Thumbnail'), ('other', 'Other')], max_length=10)),
                ('image', models.ImageField(upload_to=apps.products.models.ProductImagePath())),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
                'constraints': [models.UniqueConstraint(condition=models.Q(('image_type', 'other'), _negated=True), fields=('product', 'image_type'), name='unique_image_type_per_product')],
                'unique_together': {('product', 'image_type')},
            },
        ),
    ]
