# Generated by Django 5.2 on 2025-06-29 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderDetail', to='products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='ship_via',
            field=models.ForeignKey(blank=True, db_column='ship_via', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.shipper'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order', 'product')},
        ),
    ]
