# Generated by Django 5.2 on 2025-06-29 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('title_of_courtesy', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('territory_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('territory_description', models.CharField(max_length=255)),
                ('region', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.CASCADE, to='employees.region')),
            ],
            options={
                'db_table': 'territories',
            },
        ),
        migrations.CreateModel(
            name='EmployeeTerritory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('territory', models.ForeignKey(db_column='territory_id', on_delete=django.db.models.deletion.CASCADE, to='employees.territory')),
            ],
            options={
                'db_table': 'employee_territories',
                'unique_together': {('employee', 'territory')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='territories',
            field=models.ManyToManyField(related_name='employees', through='employees.EmployeeTerritory', to='employees.territory'),
        ),
    ]
